GCC: Put attributes before function name in partition_root.h
By GCC attributes are not allowed to be placed after function name
in a function definition. This breaks compilation in GCC.

The error example:
base/allocator/partition_allocator/partition_alloc_forward.h:80:27:
error: attributes are not allowed on a function-definition
base/allocator/partition_allocator/partition_root.h:467:7:
note: in expansion of macro 'PA_MALLOC_ALIGNED'

Bug: 819294
Change-Id: Ife233d6fe7c2bab0cd503dad5c284879d896936d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4853717
Reviewed-by: Bartek Nowierski <bartekn@chromium.org>
Commit-Queue: Ivan Murashov <ivan.murashov@lge.com>
Cr-Commit-Position: refs/heads/main@{#1194132}
NOKEYCHECK=True
GitOrigin-RevId: 3c2c77cff5f7965d6ef3b55a18400533f640b0e1