IWYU: Include <limits.h> for CHAR_BIT
This fixes the build with libstdc++ after a4c197977f ("Shatter
partition_alloc.h into smaller files").

    In file included from ../../base/allocator/partition_allocator/partition_bucket.h:11:0,
                     from ../../base/allocator/partition_allocator/partition_bucket.cc:5:
    ../../base/allocator/partition_allocator/partition_alloc_constants.h:140:53: error: ‘CHAR_BIT’ was not declared in this scope
     static const size_t kBitsPerSizeT = sizeof(void*) * CHAR_BIT;
                                                         ^~~~~~~~
    ../../base/allocator/partition_allocator/partition_alloc_constants.h:140:53: note: suggested alternative: ‘WCHAR_MIN’
     static const size_t kBitsPerSizeT = sizeof(void*) * CHAR_BIT;
                                                         ^~~~~~~~
                                                         WCHAR_MIN

Bug: 819294
Change-Id: Ie61cd7a1b55adf77e1f584bd5447ac11b6980b02
Reviewed-on: https://chromium-review.googlesource.com/1043748
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
Cr-Commit-Position: refs/heads/master@{#556034}
NOKEYCHECK=True
GitOrigin-RevId: ec4cdda75f7092f49972babbce348e168d4e12b1