[PA] Uninline sentinel slot span
This change partially undoes https://crrev.com/c/3412485, in which the
sentinel slot span was marked `inline` at its declaration inside
`SlotSpanMetadata`. This is needed to build under MSVC, which otherwise
immediately spits out

```
partition_page.h(313): error C2512:
  'partition_alloc::internal::SlotSpanMetadata<true>': no appropriate
  default constructor available
partition_bucket.h(29): note: see declaration of
  'partition_alloc::internal::SlotSpanMetadata<true>'
partition_page.h(327): note: see reference to class template
  instantiation 'partition_alloc::internal::SlotSpanMetadata<true>'
  being compiled
```

Bug: 1351310
Change-Id: I8a58be8b30c7c12bd34dcd3cdeb1040176bbd4eb
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3858985
Reviewed-by: Benoit Lize <lizeb@chromium.org>
Commit-Queue: Kalvin Lee <kdlee@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1039664}
NOKEYCHECK=True
GitOrigin-RevId: b60d5a7d8ff6f64003342c76565f081d437f2222