Revert "Reland "PartitionAlloc: Add address space metrics""
This reverts commit 548a4cc9a61667f53ccc535a17690270aa88d0ae.

Reason for revert:

I can't compile:
```
../../base/allocator/partition_allocator/address_pool_manager.cc:521:34: error: no member named 'brp_forbidden_super_page_map_' in 'partition_alloc::internal::AddressPoolManagerBitmap'
```

using:
```
target_cpu="x86"
```

Full args:
```
use_goma = true
enable_nacl = false
is_debug = false
dcheck_always_on = false
use_backup_ref_ptr = true
use_partition_alloc = true
enable_dangling_raw_ptr_checks = true
put_ref_count_in_previous_slot = true
enable_backup_ref_ptr_slow_checks = false
target_cpu = "x86"
```

Original change's description:
> Reland "PartitionAlloc: Add address space metrics"
>
> This is a reland of 48e5aa88fcb6b14026691bd9f581d5add9fcd1ff with
> the flaky unit test removed.
>
> Original change's description:
> > PartitionAlloc: Add address space metrics
> >
> > This change exposes some statistics from PA:
> >
> > 1.  GigaCage pool usage
> > 2.  Largest possible reservation (64-bit only)
> > 3.  Blocklist size (32-bit only)
> > 4.  Failures in finding allowed addresses (32-bit only)
> >
> > This change does not provide the hookups into memory infra
> > to expose these stats.
> >
> > Bug: 1239541
> > Test: base_unittests --gtest_filter="PartitionAllocAddressPoolManagerTest.*"
> > Change-Id: Ie3e01c6f8ddb5997eadb5607e87a98c9e4088732
> > Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3428258
> > Reviewed-by: Takashi Sakamoto <tasak@google.com>
> > Reviewed-by: Keishi Hattori <keishi@chromium.org>
> > Reviewed-by: Bartek Nowierski <bartekn@chromium.org>
> > Reviewed-by: Benoit Lize <lizeb@chromium.org>
> > Commit-Queue: Kalvin Lee <kdlee@chromium.org>
> > Cr-Commit-Position: refs/heads/main@{#971448}
>
> Bug: 1239541
> Change-Id: Idc9a5a2aa94012c0d59625aa8a55da48cb896075
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3469665
> Reviewed-by: Bartek Nowierski <bartekn@chromium.org>
> Commit-Queue: Kalvin Lee <kdlee@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#972242}

Bug: 1239541
Change-Id: I6da256f0b6fd2bf949f3ed478a19a15a77327688
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3471600
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Arthur Sonzogni <arthursonzogni@chromium.org>
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: Kentaro Hara <haraken@chromium.org>
Cr-Commit-Position: refs/heads/main@{#972474}
NOKEYCHECK=True
GitOrigin-RevId: 2ea6301eb632cca3331bf9340f4a266e68496b86