header-rewriter: add undefined reference to pthread_create wrapper
without this, we get linker errors caused by a DSO trying to link the hidden __wrap_pthread_create symbol present in libgcc.a